language: python
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - gcc-4.9
python:
    - 2.7
    - 3.5
before_install:
  - make install-dep
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
script:
  - TESTATTR='hypothesis,!known_failing' make coverage-gcovr.xml
after_success:
  - coveralls --exclude third-party --gcov-options '\-lp'
after_failure:
  - coveralls --exclude third-party --gcov-options '\-lp'
