language: python
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - gcc-4.9
python:
    - 2.7
    - 3.5
install:
  - make install-dep
script:
  - CXX=g++-4.9 CC=gcc-4.9 TESTATTR='hypothesis,!known_failing' make coverage-gcovr.xml
after_success:
  - coveralls --exclude third-party --gcov-options '\-lp'
after_failure:
  - coveralls --exclude third-party --gcov-options '\-lp'
