language: python
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
python:
    - 2.7
    - 3.5
before_install:
  - make install-dep
script:
  - TESTATTR='hypothesis,!known_failing' make coverage-gcovr.xml
after_success:
  - coveralls --exclude '.*zlib.*|.*bzip2.*|.*smhasher.*|.*seqan.*' --gcov-options '\-lp'
after_failure:
  - coveralls --exclude '.*zlib.*|.*bzip2.*|.*smhasher.*|.*seqan.*' --gcov-options '\-lp'
