language: python
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - gcc-4.9
env:
    global:
        - CXX=g++-4.9
        - CC=gcc-4.9
python:
    - 2.7
    - 3.5
install:
  - make install-dep
script:
  - TESTATTR='hypothesis,!known_failing' make coverage-gcovr.xml
after_success:
  - coveralls -n --exclude third-party --gcov-options '\-lp'
after_failure:
  - coveralls -n --exclude third-party --gcov-options '\-lp'
